version: "3.9"
services:
  db:
    image: postgres:16
    container_name: linktree_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: linktree
      POSTGRES_USER: linktree
      POSTGRES_PASSWORD: linktree
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:


